# Generated by Django 3.1.3 on 2020-12-10 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='owned_groups',
        ),
        migrations.AddField(
            model_name='owner',
            name='owned_groups',
            field=models.ManyToManyField(to='app.Group'),
        ),
    ]
